# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 870ba5a50da011e1317a6a2f12e07c1714edcfdbe2d3a72007545afa02b69ad5e49a4bc7b169bc877560dd975664508477b1c36a213f35cd7c949e6e955df159

test:
  secret_key_base: c74514bb5e86c0b6d7b25ea280465588208f1516ea3dace772b41dd1a42474796c82ba81f91d7364b41d5ba2fb12280c5a8cda084a6e81b52a6c3f92fdb38525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
